number1=int(input("Enter the first number:"))
number2=int(input("enter the second number:"))
number3=int(input("Enter the third number:"))
print("The sum of num1 and num2 is :" ,number1 +number2)
print("The difference when num2 is subtracted from num1 is:",number1-number2)
print("The product of num1 and num2 is:",number1*number2)
print("The quotient when num1 divided by num2 is:",number1/number2)
print("The remainder when num1 is divided by num2 is:",number1%number2)
result=((number1+number2)*number3/2)
print("The result of (num1 + num2) * num3 / 2 is: ",result)
